spring:
  application:
    name: Baemin
  jpa:
    hibernate:
      ddl-auto: none  # 테이블이 이미 있으므로 none으로 설정
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/BaeminDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: password123
  sql:
    init:
      mode: always
